name: Deploy Bot

on:
  push:
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensagem pro Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "🚀 Novo commit enviado! Deploy em andamento no Render..."}' \
          ${{ secrets.DISCORD_WEBHOOK }}
